config/routes.rb
Rails.application.routes.draw do

  root "welcome#about"

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get  '/signup',  to: 'registration#new'
  post '/signup',  to: 'registration#create'

  # for current_user
  get    '/profile/edit(.:format)', to: 'registration#edit', as: :profile
  put    '/profile(.:format)',      to: 'registration#update'
  patch  '/profile(.:format)',      to: 'registration#update'
  delete '/profile(.:format)',      to: 'registration#destroy'


  resources :chatrooms, param: :slug, except: [:destroy]
  resources :messages, only: :create

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to ENV['MY_APP_NAME'], '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="navbar-text"><%= current_user.username || 'Anonymous' %> </li>
          <li><%= link_to "Home", root_path, class: "glyphicon glyphicon-home" %></li>
        <% end %>
        <!-- <li>< % = link_to "Help",   '#' %></li> -->

        <% if current_user %>
          <li><%= link_to('Log out', logout_path,
                          method: :delete, class: "glyphicon glyphicon-log-out") %></li>
        <% else %>

          <% if request.original_url == login_url %>
            <li><%= link_to 'Sign up', signup_path, class: "glyphicon" %></li>
          <% elsif request.original_url == signup_url %>
            <li><%= link_to 'Log in', login_path, class: "glyphicon glyphicon-log-in" %></li>
          <% else %>
            <li><%= link_to 'Sign up', signup_path, class: "glyphicon" %></li>
            <li><%= link_to 'Log in', login_path, class: "glyphicon glyphicon-log-in" %></li>
          <% end %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>